### ISSUE TITLE
Return statement

### ISSUE THREAD

**Issue by Sandeepbhatt3287** [Sandeepbhatt3287/Data-structures-and-Algorithms#2]
string_compression.cpp: In function 'char duplicates(std::string)':
string_compression.cpp:20:9: error: cannot convert 'std::string' {aka 'std::__cxx11::basic_string<char>'} to 'char' in return
   20 |  return str;

**Comment by radekrudak** [comment]
Can i have this one ? PS. this would be my first issue but it's seems not that hard.

**Comment by Sandeepbhatt3287** [comment]
@radekrudak  you can check  string_compression question for this

**Comment by radekrudak** [comment]
> @radekrudak you can check string_compression question for this

What string_compression question? 
PS.Sorry for lack of response but git hub wasn't giving me any notification and I forgot to check this comments under this issue.
